project:
  type: website
  output-dir: docs
website:
  title: "Andres Romero-Bravo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">