project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
website:
  title: "Andrés Romero Bravo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
  page-footer:
    center: "©2026 Andrés Romero Bravo. All Rights Reserved."
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    anchor-sections: false
    include-after-body:
      text: |
        <script src="scroll-fade.js"></script>